#pragma once

// CMake supplies these for normal builds. The fallback keeps direct compiler
// invocations predictable: assertions-enabled builds are development builds.
#ifndef MANGAPSP_DEVELOPMENT
#  ifdef NDEBUG
#    define MANGAPSP_DEVELOPMENT 0
#  else
#    define MANGAPSP_DEVELOPMENT 1
#  endif
#endif

#ifndef MANGAPSP_PSP_RC
#  define MANGAPSP_PSP_RC 0
#endif

#ifndef MANGAPSP_ENABLE_METRICS
#  define MANGAPSP_ENABLE_METRICS MANGAPSP_DEVELOPMENT
#endif

#ifndef MANGAPSP_ENABLE_LOGGING
#  define MANGAPSP_ENABLE_LOGGING MANGAPSP_DEVELOPMENT
#endif

#ifndef MANGAPSP_HARDWARE_DIAGNOSTICS
#  define MANGAPSP_HARDWARE_DIAGNOSTICS MANGAPSP_DEVELOPMENT
#endif

#ifndef MANGAPSP_RUNTIME_DIAGNOSTICS
#  define MANGAPSP_RUNTIME_DIAGNOSTICS 0
#endif

#ifndef MANGAPSP_BOOT_DIAGNOSTICS
#  define MANGAPSP_BOOT_DIAGNOSTICS 0
#endif

#ifndef MANGAPSP_BOOT_HOLD_STAGE
#  define MANGAPSP_BOOT_HOLD_STAGE 0
#endif

#ifndef MANGAPSP_BOOT_HOLD_CHECKPOINT
#  define MANGAPSP_BOOT_HOLD_CHECKPOINT 0
#endif

#ifndef MANGAPSP_DEFER_PSP_INPUT_SETUP
#  define MANGAPSP_DEFER_PSP_INPUT_SETUP 0
#endif

#ifndef MANGAPSP_DISABLE_CBZ
#  define MANGAPSP_DISABLE_CBZ 0
#endif

#ifndef MANGAPSP_DISABLE_THUMBNAILS
#  define MANGAPSP_DISABLE_THUMBNAILS 0
#endif

#ifndef MANGAPSP_IGNORE_PERSISTENCE
#  define MANGAPSP_IGNORE_PERSISTENCE 0
#endif

#ifndef MANGAPSP_FORCE_NO_MANGA
#  define MANGAPSP_FORCE_NO_MANGA 0
#endif

#ifndef MANGAPSP_HOLD_AFTER_FOLDER_SCAN
#  define MANGAPSP_HOLD_AFTER_FOLDER_SCAN 0
#endif

#define MANGAPSP_BOOT_TRACE_ACTIVE \
    (MANGAPSP_BOOT_DIAGNOSTICS && (MANGAPSP_DEVELOPMENT || MANGAPSP_PSP_RC))
